# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20161007_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('R', 'Returned'), ('PB', 'Pre-booked'), ('I', 'Issued')], default='PB', max_length=2),
        ),
    ]
