# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_receipt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 10, 24, 11, 18, 51, 9851))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.subscriber')),
            ],
        ),
    ]
