# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='author', max_length=60),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 6, 38, 46, 103899)),
        ),
    ]
