# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20161030_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 1, 8, 1, 14, 325012)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='pno',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='reg_no',
            field=models.IntegerField(default=None),
        ),
    ]
