# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20161101_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 11, 18, 22, 40, 748945)),
        ),
    ]
