# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20161112_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 2, 42, 52, 805289)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='pno',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='reg_no',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
