# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20161112_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='hostel',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 15, 17, 22, 7, 526334)),
        ),
    ]
