# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20161115_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='room',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='hostel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
